apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-order
spec:
  schedule: "* 1 * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
          - name: generate-order
            image: registry.gitlab.com/zl0i/restaurantloadgenerator/app:latest
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred  
